name: Sync Code to AWS CodeCommit

on:
  push:
    branches:
      - '*'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_USERNAME }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PASSWORD }}
          AWS_REGION: ap-southeast-1  # Change to your desired AWS region
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_REGION

      - name: Add CodeCommit remote
        run: |
          git remote add codecommit https://git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/Watiga-Demo

      - name: Push code to CodeCommit
        run: |
          git push codecommit HEAD:refs/heads/master