name: Sync Code to AWS CodeCommit

on:
  push:
    branches:
      - '*'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        env:
          AWS_REGION: ap-southeast-1  # Change to your desired AWS region
        run: |
          git config --global credential.helper '!aws codecommit credential-helper $@'
          git config --global credential.UseHttpPath true
          git config --global user.name ${{ secrets.AWS_USERNAME }}
          git config --global user.password ${{ secrets.AWS_PASSWORD }}

      - name: Add CodeCommit remote
        run: |
          git remote add codecommit https://git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/Watiga-Demo

      - name: Push code to CodeCommit
        run: |
          git push codecommit HEAD:refs/heads/master