name: Sync to CodeCommit
on:
  push:
    branches:
      - '*'  # Adjust this to the branch you want to sync

jobs:
  sync_to_codecommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync to AWS CodeCommit
        run: |
          # Replace 'your-aws-codecommit-repo' with the name of your CodeCommit repository
          aws codecommit create-repository --repository-name Demo
          git remote add awscodecommit https://git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/Demo
          git push awscodecommit HEAD:refs/heads/main  # Adjust the branch name if necessary
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-1